{
	"country":	"Country",
	"exchange":	"Exchange",
	"os":		"OS",
	"osv":		"OS Version",
	"gender":	"Gender",
	"devtype":	"Device Type",
	"conntype":	"Connection Type",
	"medtype":	"Medium Type",
	"crid":		"Creative ID",
	"lid":		"Link ID",
	"medid":	"Medium ID",
	"medname":	"Medium Name",
	"meddomain":	"Medium Domain",
	"pubid":	"Publisher ID",
	"pubname":	"Publisher Name",
	"pubdomain":	"Publisher Domain",
	"carrier":	"Carrier",
	"browser":	"Browser",
	"plcw":		"Placement Width",
	"plch":		"Placement Height",
	"mime":		"MIME",
	"devmake":	"Device Make",
	"devmodel":	"Device Model",
	"devids":	"Device Ids",
	"age":		"Age",
	"sessdepth":	"Session Depth",
	"freqdepth":	"Frequency Depth",
	"iab_cats":	"IAB Categories"
}
