{
	"IAB3": "Arts & Entertainment",
	"IAB2": "Automotive",
	"IAB3": "Business",
	"IAB4": "Careers",
	"IAB5": "Education",
	"IAB6": "Family & Parenting",
	"IAB7": "Health & Fitness",
	"IAB8": "Food & Drink",
	"IAB9": "Hobbies & Interests",
	"IAB10": "Home & Garden",
	"IAB11": "Law / Politics",
	"IAB12": "News",
	"IAB13": "Personal Finance",
	"IAB14": "Society / Dating",
	"IAB15": "Science",
	"IAB16": "Pets",
	"IAB17": "Sports",
	"IAB18": "Style & Fashion",
	"IAB19": "Technology",
	"IAB20": "Travel",
	"IAB21": "Real Estate",
	"IAB22": "Shopping",
	"IAB23": "Religion & Spirituality"
}
